name: Shopify Discount Scheduler

on:
  schedule:
    - cron: '0 1 * * *'  # UTC时间1点，对应北京时间上午9点
  workflow_dispatch:     # 手动触发支持

jobs:
  run-discount-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download yesterday discounts
        uses: actions/download-artifact@v4
        with:
          name: yesterday-discounts
          path: .
        continue-on-error: true

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - run: pip install -r requirements.txt

      - name: Run script
        env:
          SHOPIFY_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          SHOPIFY_STORE_URL: ${{ secrets.STORE_URL }}
        run: python main.py

      - name: Upload yesterday discounts
        uses: actions/upload-artifact@v4
        with:
          name: yesterday-discounts
          path: yesterday_discounts.json
